REM THIS IS SETUP TO CHECK BITNESS OF OUTLOOK
REM CHANGE THE KEY NAMES TO DIFFERENT SOFTWARE
REM TO CHECK THOSE. ENSURE THEY HAVE THE "Bitness" VALUE


SET OTHER_KEY_NAME=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Office\15.0\Outlook
SET KEY_NAME=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\15.0\Outlook
SET VALUE_NAME=Bitness

FOR /F "usebackq tokens=3" %%A IN (`reg query "%OTHER_KEY_NAME%" /v "%VALUE_NAME%"`) DO SET OTHERVALUE=%%A
FOR /F "usebackq tokens=3" %%A IN (`reg query "%KEY_NAME%" /v "%VALUE_NAME%" 2^>nul ^| FIND "%VALUE_NAME%"`) DO SET VALUE=%%A

SET "bitness="
IF DEFINED OTHERVALUE SET bitness=%OTHERVALUE%
IF DEFINED VALUE SET bitness=%VALUE%

IF DEFINED bitness (
	if %bitness%==x86 (
		REM 32 BIT SOFTWARE INSTALLED 
	) else (
		REM 64 BIT SOFTWARE INSTALLED
	)
)